# Generated by Django 6.0.3 on 2026-03-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='test', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='test', max_length=220),
        ),
    ]
