# Generated by Django 6.0.3 on 2026-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
