# Generated by Django 6.0.3 on 2026-03-25 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_subscription_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_gallery/', verbose_name='Фото')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='Новина')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Галерея фотографій',
            },
        ),
    ]
